### ISSUE TITLE
Development plans

### ISSUE THREAD

**Issue by colderlord** [markjackmilian/Bridge.Ioc#2]
Hello!
Tell us about your plans for development.
Project will continue to develop?
Thank you!

**Comment by markjackmilian** [comment]
This project was born as part of a wider architecture. The largest project is called SPAF and you can find it here (I have no documentation or examples yet).
SPAF is a small framework for creating single page applications built on the top of Bridge.
SPAF today consists of a navigation service (Bridge. Navigation) a messaging in process (Bridge. MEssenger), help and architecture components (Bridge. Spaf) and an IOC (Bridge. Ioc).
The combination of these services allows you to create SPA applications with elegant architecture.
This project has therefore implemented the APIs necessary for its use within SPAF and will be extended upon request or when the main project will need new APIs.
PS i built 2 applications with SPAf that are currently in production with excellent results, I hope to create documentation and examples in the coming weeks.
